POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Johnny Fontes Rabelo",
    "email": "johnny.rabelo.cf@gmail.com",
    "password": "130508",
    "cpf": "12345678901",
    "phone": "12345678901"
}

###

GET http://localhost:3000/users

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "johnny.rabelo.cf@gmail.com",
    "password": "130508"
}

###

POST http://localhost:3000/accounts/johnny.rabelo.cf@gmail.com
Content-Type: application/json

{
    "currentValue": 1000,
    "currency": "BRL"
}

###

POST http://localhost:3000/transactions
Content-Type: application/json

{
    "value": 100,
    "type": "input",
    "destination": "Teste",
    "description": "Teste",
    "accountId": 
{